# DX 602 Week 7 Homework



## Introduction

In this homework, you will continue practicing the NumPy library to work with numbers in various ways.
There will be a particular focus on views, but you will also be asked to find and recognize relevant NumPy functions on your own.
NumPy is a large library with a lot of different functionality.
It is impractical to introduce each function individually, yet you will be able to make use of most of its functionality with a basic exercise of search skills.


## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [126]:
import math
import sys

In [127]:
import matplotlib.pyplot as plt
import numpy as np

## Problems

### Problem 1

Set `p1` to be `q1` flipped upside down.

In [128]:
# DO NOT CHANGE

q1 = np.array([[9, 1, 6], [2, 6, 3], [5, 0, 7]])

In [129]:
# YOUR CHANGES HERE

p1 = ...

In [130]:
p1

Ellipsis

### Problem 2

Set `p2` to be the average value of `q2`.

In [131]:
# DO NOT CHANGE

q2 = np.array([[ 1.2710684 ,  0.34651747,  0.68960684, -1.12567075, -0.06412985,
         0.13373547,  0.84314528,  0.35206589],
       [-1.18745615,  0.50656175,  0.66699453,  0.72676468, -0.34165581,
        -1.00205835,  0.02101389,  0.93188219],
       [ 0.23127874, -0.32878023, -0.97939304,  0.01044438, -0.81895036,
        -0.44674951,  0.87667202, -1.51737553],
       [ 2.07266937, -1.63841334, -0.20043649,  1.01993301, -1.21509526,
        -0.15027553,  0.39621876,  0.28836095],
       [-0.83933974,  1.64994802, -0.1213623 ,  0.25179499,  1.0813766 ,
         0.48275638, -1.41171727, -0.72633164],
       [-0.38257196,  0.12212784,  0.73860358, -1.61096579, -0.38644903,
         0.30642748,  0.92550333, -2.20470762],
       [ 0.32864359,  0.8622356 ,  1.99156784,  0.2118577 , -0.58876625,
        -1.01185141,  0.83046577, -0.48243025],
       [ 0.31960012,  0.60696688,  0.68950522, -0.80539561, -1.04918003,
         0.2794904 , -0.09944267,  0.31027322]])
q2

array([[ 1.2710684 ,  0.34651747,  0.68960684, -1.12567075, -0.06412985,
         0.13373547,  0.84314528,  0.35206589],
       [-1.18745615,  0.50656175,  0.66699453,  0.72676468, -0.34165581,
        -1.00205835,  0.02101389,  0.93188219],
       [ 0.23127874, -0.32878023, -0.97939304,  0.01044438, -0.81895036,
        -0.44674951,  0.87667202, -1.51737553],
       [ 2.07266937, -1.63841334, -0.20043649,  1.01993301, -1.21509526,
        -0.15027553,  0.39621876,  0.28836095],
       [-0.83933974,  1.64994802, -0.1213623 ,  0.25179499,  1.0813766 ,
         0.48275638, -1.41171727, -0.72633164],
       [-0.38257196,  0.12212784,  0.73860358, -1.61096579, -0.38644903,
         0.30642748,  0.92550333, -2.20470762],
       [ 0.32864359,  0.8622356 ,  1.99156784,  0.2118577 , -0.58876625,
        -1.01185141,  0.83046577, -0.48243025],
       [ 0.31960012,  0.60696688,  0.68950522, -0.80539561, -1.04918003,
         0.2794904 , -0.09944267,  0.31027322]])

In [132]:
p2 = ...

In [133]:
p2

Ellipsis

### Problem 3

Write a function `p3` that takes in a 2-dimensional array and returns an array with the even columns of the input array.


In [134]:
# YOUR CHANGES HERE

def p3(x):
    ...

In [135]:
# the output should have values [[0, 2, 4]]
p3(np.array([[0, 1, 2, 3, 4]]))

In [136]:
p3(np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]))

### Problem 4

Write a function `p4` taking in a 2-dimensional array, and returning a 1-dimensional array with every 5th element of a row-order traversal of the input, starting from the 3rd element.

In [137]:
# YOUR CHANGES HERE

def p4(x):
    ...

In [138]:
x4 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [139]:
# this should return a 1-dimensional array with contents [2, 7, 12]

p4(x4)

### Problem 5

What NumPy function evaluates the Einstein summation convention?
Set `p5` to be a reference to that function.
You can look for this function by using NumPy site documentation and search, or other search engines.

In [140]:
# YOUR CHANGES HERE

p5 = ...

In [141]:
p5

Ellipsis

### Problem 6

Write a function `p6` that takes in two inputs, a function and an array, and returns `True` if calling that function with the array as input returns a view of that array and `False` otherwise.

In [142]:
# YOUR CHANGES HERE

def p6(f, x):
    ...

In [143]:
p6(np.sum, np.arange(20))

In [144]:
p6(np.fliplr, np.zeros((3, 4)))

### Problem 7

Write a function `p7` that takes in an array, and if it is a view, returns a number indicating the proportion of the original array that is seen through the view, and returns `None` if the array is not a view.
If the input is an array of 10 elements, and it is a view of an array of 20 elements, your function should return 0.5.


In [145]:
# YOUR CHANGES HERE

def p7(x):
    ...

In [146]:
# a view

t7a = np.arange(20)
t7b = t7a[::2]
p7(t7b)

In [147]:
# not a view

p7(np.arange(20))

### Problem 8

Write a function `p8` that returns the diagonal of an input 2-dimensional array. The diagonal of an array $x$ is the elements $x[0][0], x[1][1], x[2][2], \ldots$.


In [148]:
# YOUR CHANGES HERE

def p8(x):
    ...

In [149]:
p8(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

### Problem 9

Write a function `p9` that returns a view of the diagonal of an input 2-dimensional array but it must return a view of the original array. (If your previous answer already returned a view, you may reuse it.)

In [150]:
# YOUR CHANGES HERE

def p9(x):
    ...

In [151]:
x9 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [152]:
p9(x9)

In [153]:
# uncomment to test after you finish p9

# p9(x9).base is x9

### Problem 10

The [$X + Y$ sorting problem](https://en.wikipedia.org/wiki/X_%2B_Y_sorting) considers the problem of sorting pairs of numbers from two lists of numbers, $X$ and $Y$, by their sums.
Write a function `p10` that takes in two 1-dimensional arrays, $x$ and $y$, and returns a two dimensional array $z$ such that $z[i,j] = x[i] + y[j]$.

Hint: use broadcasting.

In [154]:
# YOUR CHANGES HERE

def p10(x, y):
    ...

In [155]:
p10(np.array([10, 20, 30]), np.array([1, 2, 3, 4, 5]))

### Problem 11

Write a function `p11` taking an $n \times k$ array and returns an $n \times 3$ array where the first column is the minimum value of the input rows, the second column is the median of the input rows, and the third column is the maximum values of the input rows.


Hint: there was a similar problem in week 6, but you will need `numpy.reshape` and `numpy.hstack` to adapt those results.


In [156]:
def p11(x):
    ...

In [157]:
p11([[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]])

### Problem 12

What does the following code do?

```
def f12(vs):
    return [v for (i, v) in enumerate(vs) if i >= 5]

def g12(n):
    for i in range(n):
        yield i ** 2

print(f12(g12(10)))
```

Set `p12` to the printed output.

In [158]:
# YOUR CHANGES HERE

p12 = ...

In [159]:
p12

Ellipsis

### Problem 13

The following code is supposed to iterate the Collatz function until it reaches the value 1, but does not have the correct control flow.
Modify the loop below so that it continues until the last entry of `p13` is one.

In [160]:
# DO NOT CHANGE

def f13(x):
    if x % 2 == 0:
        # even case
        return x // 2
    else:
        return 3 * x + 1

In [161]:
# DO NOT CHANGE

p13 = [27]

In [162]:
# YOUR CHANGES HERE

while len(p13) < 10:
    # apply f13() to the last entry of p13.
    p13.append(f13(p13[-1]))

In [163]:
p13

[27, 82, 41.0, 124.0, 62.0, 31.0, 94.0, 47.0, 142.0, 71.0]

### Problem 14

Set `p14` to be the shape tuple of the variable `q14` at the end of the following code.

```
q14 = np.arange(24)
q14 = q14.reshape(3, -1)
q14 = q14[:,::3]
```

In [164]:
# YOUR CHANGES HERE

p14 = ...

In [165]:
p14

Ellipsis

### Problem 15

The array `q15` below was filled with a sample of random numbers.
The variable `p15` is a reference to the same array.
Change the contents of `p15` so that the first row is all zeros.
After your change to `p15`, the variables `p15` and `q15` should still be the same array.

Hint: use row indexing to easily overwrite just one row of `p15`.

In [166]:
# DO NOT CHANGE

q15 = np.array([[ 1.76435665, -0.66892705, -1.08485379, -0.51982851,  1.2362559 ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])
p15 = q15
p15

array([[ 1.76435665, -0.66892705, -1.08485379, -0.51982851,  1.2362559 ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])

In [167]:
# YOUR CHANGES HERE

...

Ellipsis

In [168]:
p15

array([[ 1.76435665, -0.66892705, -1.08485379, -0.51982851,  1.2362559 ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])

In [360]:
# confirm that p15 is still the same array
id(p15) == id(q15)

True

### Problem 16

Write a function `p16` that takes in numbers of rows and columns and a value, and uses `np.broadcast_to` to make a 2-dimensional array of the specified size that appears to have the specified dimensions and each has the given value.
This will be similar to the output of `np.full`, except the resulting array will be read-only because of the broadcast usage.

In [ ]:
# YOUR CHANGES HERE

def p16(rows, columns, value):
    ...

In [ ]:
t16 = p16(3, 4, 5)
t16

### Problem 17

Set `p17` to the contents of `q17` after running the following code.

```
q17 = np.arange(16)
q17 = q17.reshape(-1, 4)
q17 = np.flipud(q17)
q17 = np.fliplr(q17)
```

In [ ]:
# YOUR CHANGES HERE

p17 = ...

In [ ]:
p17

### Problem 18

Write a function `p18` that takes in a size $n$ and returns a 1-dimensional array of length $n$ where the first element is $1$ and the $i+1$th element is the $i$th element plus $1/(i+1)$.
Make sure to test your function on at least $n=1000000$.

In [33]:
# YOUR CHANGES HERE

def p18(n):
    ...

In [ ]:
# should return array with contents [1, 1.5]
p18(2)

In [ ]:
p18(5)

In [34]:
# this will be very slow if your function repeatedly builds fresh arrays.
# p18(1000000)

### Problem 19

Write a function `p19` that takes in 3 values $a$, $b$, and $c$ and an array $X$ and returns $a X^2 + bX + c$.
`p19` should return an array in the same shape as the input $X$.

In [ ]:
# YOUR CHANGES HERE

def p19(a, b, c, X):
    ...


In [ ]:
p19(1, 0, 0, np.arange(0, 10))

In [ ]:
p19(0, 0, 1, np.arange(0, 10))

In [ ]:
p19(1, 2, 3, np.arange(0, 10))

### Problem 20

Write a function `p20` taking in input array $X$ and return $X X^T$ where $X^T$ denotes matrix transposition, and $X X^T$ denotes combining $X$ and $X^T$ with matrix multiplication.


In [35]:
# YOUR CHANGES HERE

def p20(X):
    ...

In [ ]:
# should return
# [[1, 2, 3, 4, 5],
#  [2, 4, 6, 8, 10],
#  [3, 6, 9, 12, 15],
#  [4, 8, 12, 16, 20],
#  [5, 10, 15, 20, 25]]

p20(np.array([[1], [2], [3], [4], [5]]))


In [ ]:
# should return
# [[ 2,  3,  4,  5,  6],
#  [ 3,  5,  7,  9, 11],
#  [ 4,  7, 10, 13, 16],
#  [ 5,  9, 13, 17, 21],
#  [ 6, 11, 16, 21, 26]]

p20(np.array([[1, 1], [2, 1], [3, 1], [4, 1], [5, 1]]))